version: "3.3"
services:
  api:
    build: ./Backend/
    ports:
      - 8081:8081

  website:
    build: ./Frontend/website
    ports:
      - 3000:3000
    expose:
      - "3000"

  admin:
    build: ./Frontend/admin
    ports:
      - 3001:3001
    expose:
      - "3001"
    env_file:
      - ./Frontend/admin/.env.development

 